swagger: '2.0'
info:
  description: Consultas de DNI y RUC - Perú
  version: '3.0'
  title: PERU CONSULTAS
  contact:
    email: giansalex@gmail.com
host: consult.api
basePath: /api/v1
tags:
  - name: RENIEC
    description: Registro Nacional de Identificación y Estado Civil.
  - name: SUNAT
    description: Superintendencia Nacional de Aduanas y de Administración Tributaria.
  - name: GraphQL
    description: 'Lenguaje de consulta para APIs, disponible para RUC y DNI.'
schemes:
  - http
  - https
security:
  - ApiToken: []
securityDefinitions:
  ApiToken:
    name: token
    type: apiKey
    in: query
    description: Api Token
